%%% clustergramming.m

clear all;
close all;
clc;

cmap = redblue(100);

load('ensemble/output_1.mat', 'J');

clusters_1 = clustergram(J, 'Colormap', cmap, ...
                'Cluster', 'row', ...
                'Standardize','None', ...
                'DisplayRange',2, ...
                'ShowDendrogram','on', ...
                'OptimalLeafOrder','true');
set(clusters_1,'Linkage','Ward','Dendrogram',2);

clusters_2 = clustergram(J, 'Colormap', cmap, ...
                'Cluster', 'column', ...
                'Standardize','None', ...
                'DisplayRange',2, ...
                'ShowDendrogram','on', ...
                'OptimalLeafOrder','true');
set(clusters_2,'Linkage','Ward','Dendrogram',2);

clusters_3 = clustergram(J, 'Colormap', cmap, ...
                'Cluster', 'all', ...
                'Standardize','None', ...
                'DisplayRange',2, ...
                'ShowDendrogram','on', ...
                'OptimalLeafOrder','true');
set(clusters_3,'Linkage','Ward','Dendrogram',2);
